import { Blue, Yellow } from "../../../../../colors/colorsApp";

export const memorama_utilities = {
    opc_1: [
        { order: 1, text: 1, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 2, text: 2, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 3, text: 3, icon: '../../../../../../assets/games/memorama/par_3.png', color: Blue, opened: false, completed: false },
        { order: 4, text: 4, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 5, text: 5, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 6, text: 6, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 7, text: 7, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 8, text: 8, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 9, text: 9, icon: '../../../../../../assets/games/memorama/par_3.png', color: Blue, opened: false, completed: false },
        { order: 10, text: 10, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 11, text: 11, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 12, text: 12, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
    ],
    opc_2: [
        { order: 1, text: 1, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 2, text: 2, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 3, text: 3, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 4, text: 4, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 5, text: 5, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 6, text: 6, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 7, text: 7, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 8, text: 8, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 9, text: 9, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 10, text: 10, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 11, text: 11, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 12, text: 12, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 13, text: 13, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
        { order: 14, text: 14, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 15, text: 15, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 16, text: 16, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
    ],
    opc_3: [
        { order: 1, text: 1, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 2, text: 2, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 3, text: 3, icon: '../../../../../../assets/games/memorama/par_9.png', color: '#FF84DF', opened: false, completed: false },
        { order: 4, text: 4, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 5, text: 5, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 6, text: 6, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 7, text: 7, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 8, text: 8, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 9, text: 9, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 10, text: 10, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
        { order: 11, text: 11, icon: '../../../../../../assets/games/memorama/par_10.png', color: Yellow, opened: false, completed: false },
        { order: 12, text: 12, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 13, text: 13, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 14, text: 14, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 15, text: 15, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 16, text: 16, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 17, text: 17, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
        { order: 18, text: 18, icon: '../../../../../../assets/games/memorama/par_10.png', color: Yellow, opened: false, completed: false },
        { order: 19, text: 19, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 20, text: 20, icon: '../../../../../../assets/games/memorama/par_9.png', color: '#FF84DF', opened: false, completed: false },
    ],
    opc_4: [
        { order: 1, text: 1, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 2, text: 2, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 3, text: 3, icon: '../../../../../../assets/games/memorama/par_11.png', color: '#AA1200', opened: false, completed: false },
        { order: 4, text: 4, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 5, text: 5, icon: '../../../../../../assets/games/memorama/par_12.png', color: '#5AC12A', opened: false, completed: false },
        { order: 6, text: 6, icon: '../../../../../../assets/games/memorama/par_13.png', color: '#FF8B00', opened: false, completed: false },
        { order: 7, text: 7, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 8, text: 8, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 9, text: 9, icon: '../../../../../../assets/games/memorama/par_10.png', color: Yellow, opened: false, completed: false },
        { order: 10, text: 10, icon: '../../../../../../assets/games/memorama/par_4.png', color: '#000', opened: false, completed: false },
        { order: 11, text: 11, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 12, text: 12, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 13, text: 13, icon: '../../../../../../assets/games/memorama/par_3.png', color: '#F04B41', opened: false, completed: false },
        { order: 14, text: 14, icon: '../../../../../../assets/games/memorama/par_7.png', color: '#7F32B4', opened: false, completed: false },
        { order: 15, text: 15, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
        { order: 16, text: 16, icon: '../../../../../../assets/games/memorama/par_5.png', color: '#C396D0', opened: false, completed: false },
        { order: 17, text: 17, icon: '../../../../../../assets/games/memorama/par_10.png', color: Yellow, opened: false, completed: false },
        { order: 18, text: 18, icon: '../../../../../../assets/games/memorama/par_14.png', color: '#2A98C1', opened: false, completed: false },
        { order: 19, text: 19, icon: '../../../../../../assets/games/memorama/par_9.png', color: '#FF84DF', opened: false, completed: false },
        { order: 20, text: 20, icon: '../../../../../../assets/games/memorama/par_2.png', color: '#E23D26', opened: false, completed: false },
        { order: 21, text: 21, icon: '../../../../../../assets/games/memorama/par_9.png', color: '#FF84DF', opened: false, completed: false },
        { order: 22, text: 22, icon: '../../../../../../assets/games/memorama/par_12.png', color: '#5AC12A', opened: false, completed: false },
        { order: 23, text: 23, icon: '../../../../../../assets/games/memorama/par_14.png', color: '#2A98C1', opened: false, completed: false },
        { order: 24, text: 24, icon: '../../../../../../assets/games/memorama/par_8.png', color: '#000', opened: false, completed: false },
        { order: 25, text: 25, icon: '../../../../../../assets/games/memorama/par_15.png', color: Blue, opened: false, completed: false },
        { order: 26, text: 26, icon: '../../../../../../assets/games/memorama/par_6.png', color: '#298243', opened: false, completed: false },
        { order: 27, text: 27, icon: '../../../../../../assets/games/memorama/par_11.png', color: '#AA1200', opened: false, completed: false },
        { order: 28, text: 28, icon: '../../../../../../assets/games/memorama/par_1.png', color: '#9DCE0E', opened: false, completed: false },
        { order: 29, text: 29, icon: '../../../../../../assets/games/memorama/par_13.png', color: '#FF8B00', opened: false, completed: false },
        { order: 30, text: 30, icon: '../../../../../../assets/games/memorama/par_15.png', color: Blue, opened: false, completed: false },
    ],
    cards: [
        {
            id: 1,
            tipo: 'Fácil',
            pares: 6,
            selected: true,
        },
        {
            id: 2,
            tipo: 'Normal',
            pares: 8,
            selected: false,
        },
        {
            id: 3,
            tipo: 'Difícil',
            pares: 10,
            selected: false,
        },
        {
            id: 4,
            tipo: 'Extremo',
            pares: 15,
            selected: false,
        },
    ],
}