export {default as navigationSlice} from './navigationSlice'
export {default as orientationSlice} from './orientationSlice'
export {default as ticketSlice} from './ticketSlice'
export {default as prenominaSlice} from './prenominaSlice'
export {default as nominaSlice} from './nominaSlice'
export {default as vacationSlice} from './vacationSlice'
export {default as worldCupSlice} from './worldCupSlice'
export {default as varSlice} from './varSlice'