export const puzzle_utilities = {
    opc_1: [
        { order: 1, text: 1, match: false },
        { order: 2, text: 2, match: false },
        { order: 3, text: 3, match: false },
        { order: 4, text: 4, match: false },
        { order: 5, text: 5, match: false },
        { order: 6, text: 6, match: false },
        { order: 7, text: 7, match: false },
        { order: 8, text: 8, match: false },
        { order: 9, text: 9, match: false },
        { order: 10, text: 10, match: false },
        { order: 11, text: 11, match: false },
        { order: 12, text: 12, match: false },
        { order: 13, text: 13, match: false },
        { order: 14, text: 14, match: false },
        { order: 15, text: 15, match: false },
        { order: 16, text: '', match: false },
    ],
    opc_2: [
        { order: 1, text: 1, match: false },
        { order: 2, text: 5, match: false },
        { order: 3, text: 9, match: false },
        { order: 4, text: 13, match: false },
        { order: 5, text: 2, match: false },
        { order: 6, text: 6, match: false },
        { order: 7, text: 10, match: false },
        { order: 8, text: 14, match: false },
        { order: 9, text: 3, match: false },
        { order: 10, text: 7, match: false },
        { order: 11, text: 11, match: false },
        { order: 12, text: 15, match: false },
        { order: 13, text: 4, match: false },
        { order: 14, text: 8, match: false },
        { order: 15, text: 12, match: false },
        { order: 16, text: '', match: false },
    ],
    opc_3: [
        { order: 1, text: 1, match: false },
        { order: 2, text: 3, match: false },
        { order: 3, text: 6, match: false },
        { order: 4, text: 10, match: false },
        { order: 5, text: 2, match: false },
        { order: 6, text: 5, match: false },
        { order: 7, text: 9, match: false },
        { order: 8, text: 13, match: false },
        { order: 9, text: 4, match: false },
        { order: 10, text: 8, match: false },
        { order: 11, text: 12, match: false },
        { order: 12, text: 15, match: false },
        { order: 13, text: 7, match: false },
        { order: 14, text: 11, match: false },
        { order: 15, text: 14, match: false },
        { order: 16, text: '', match: false },
    ],
    opc_4: [
        { order: 1, text: '', match: false },
        { order: 2, text: 15, match: false },
        { order: 3, text: 14, match: false },
        { order: 4, text: 13, match: false },
        { order: 5, text: 5, match: false },
        { order: 6, text: 4, match: false },
        { order: 7, text: 3, match: false },
        { order: 8, text: 12, match: false },
        { order: 9, text: 6, match: false },
        { order: 10, text: 1, match: false },
        { order: 11, text: 2, match: false },
        { order: 12, text: 11, match: false },
        { order: 13, text: 7, match: false },
        { order: 14, text: 8, match: false },
        { order: 15, text: 9, match: false },
        { order: 16, text: 10, match: false },
    ],
    cards: [
        {
            id: 1,
            puntos: 500,
            tipo: 'Clásico',
            selected: true,
        },
        {
            id: 2,
            puntos: 1000,
            tipo: 'Intermedio',
            selected: false,
        },
        {
            id: 3,
            puntos: 1500,
            tipo: 'Avanzado',
            selected: false,
        },
        {
            id: 4,
            puntos: 2000,
            tipo: 'Experto',
            selected: false,
        },
    ],
}